# Generated by Django 4.2.3 on 2023-07-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New_preject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.TextField(verbose_name='file_name')),
                ('file_size', models.IntegerField(verbose_name='file_size')),
                ('format_file', models.CharField(max_length=50, verbose_name='format_file')),
            ],
        ),
    ]
